import React, { useState } from 'react';

const API_URL = 'http://localhost:3001/api/solve';

function MetricCard({ label, value }) {
  return (
    <div className="metric-card">
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}

export default function App() {
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function runSolver() {
    setLoading(true);
    setError('');
    setResult(null);

    try {
      const response = await fetch(API_URL);
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Solver request failed');
      }

      setResult(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="page">
      <section className="header">
        <div>
          <h1>Campus Scheduler</h1>
          <p>Optimized energy-aware schedule generated by SWI-Prolog.</p>
        </div>
        <button onClick={runSolver} disabled={loading}>
          {loading ? 'Running...' : 'Run Solver'}
        </button>
      </section>

      {error && <div className="error">{error}</div>}

      {result && (
        <>
          <section className="metrics" aria-label="Optimization metrics">
            <MetricCard label="Score" value={result.score} />
            <MetricCard label="Total Energy" value={result.totalEnergy} />
            <MetricCard label="Load Imbalance" value={result.loadImbalance} />
            <MetricCard label="Room Usage Imbalance" value={result.roomUsageImbalance} />
          </section>

          <section className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Course</th>
                  <th>Session</th>
                  <th>Room</th>
                  <th>Start Time</th>
                  <th>Occupied Slots</th>
                </tr>
              </thead>
              <tbody>
                {result.schedule.map((item, index) => (
                  <tr key={`${item.course}-${item.session}-${index}`}>
                    <td>{item.course}</td>
                    <td>{item.session}</td>
                    <td>{item.room}</td>
                    <td>{item.startTime}</td>
                    <td>{item.occupiedSlots.join(', ')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        </>
      )}
    </main>
  );
}
